FLASK_APP='manage.py'
FLASK_ENV=development
SECRET_KEY='my_master_key'
DB_HOST=localhost
DB_USERNAME='flask_user'
DB_PASSWORD='12345'
DATABASE_NAME='flogger_db'
POSTGRES_ROOT_PASSWORD=root
BLOG_NAME='The Flogger Blog'
BLOG_POST_IMAGES_PATH = '/FlaskDev/flogger/static/images/uploads'