FLASK_APP='manage.py'
FLASK_ENV=development
SECRETE_KEY='you-will-never-guess'
DB_USERNAME=flaskUser
DB_PASSWORD=12345
DB_HOST=localhost
DATABASE_NAME=flogger
POSTGRES_ROOT_PASSWORD=12345
BLOG_NAME='The flogger Blog'
BLOG_POST_IMAGES_PATH='C:\Users\crhdr\Documents\projects\FlaskDev\flogger\static\images\uploads'